### ISSUE TITLE
Mount fails for size > 16MB

### ISSUE THREAD

**Issue by nzottmann** [rickkas7/SpiffsParticleRK#5]
I use a MX25L51245GMI-08G flash chip with 64MBytes. The mount fails if I use a size > 16MB:
```cpp
fs.withPhysicalSize(17 * 1024 * 1024);
```

```
[...]
erase 010fe000:4096
erase 010ff000:4096
0000318890 [app.spiffs] INFO: format res=0
SPIFFS_mount  sz:17825792 logpgsz:256 logblksz:4096 perasz:4096 addr:00000000 fdsz:128 cachesz:1192
0000318893 [app.spiffs] INFO: mount after format res=-10025
```

Using a size <= 16MBytes, it works as expected:
```cpp
fs.withPhysicalSize(2 * 1024 * 1024);
```
```
[...]
erase 001fe000:4096
erase 001ff000:4096
0000021171 [app.spiffs] INFO: format res=0
SPIFFS_mount  sz:2097152 logpgsz:256 logblksz:4096 perasz:4096 addr:00000000 fdsz:128 cachesz:1192
page index byte len:         256
object lookup pages:         1
page pages per block:        16
page header length:          5
object header index entries: 105
object index entries:        124
available file descriptors:  2
free blocks:                 512
0000021320 [app.spiffs] INFO: mount after format res=0
```

Using `spiFlash.chipErase();` or `fs.erase();` before mounting as suggested in #2 if changing the filesystem size did not change anything and was not necessary for changing the filesystem size, as long as I kept it below 16MBytes.

The README says
> The chips are really inexpensive [...]. They're available in **sizes up to 16 Mbyte**.

Is there a limit in the library not supporting chips > 16MBytes? As I found a 64MByte chip, this seems to be outdated. Or am I interpreting the size of the chip wrong?

**Comment by rickkas7** [comment]
The 16 MB limit is fixed in the version of SPIFFS that I forked. The reason is the logical page size is 256 bytes and the size of the logical page index is a uint16_t so 256 * 65536 = 16777216 = 16 MB.

In theory, the logical page size could be changed, however it would reduce efficiency on smaller devices, and since it's a #define I can't easily change it at runtime based on the device size.

You could try making a fork with it changed and see if it works.
